version: '3.9'

services:

  web:
    build:
      context: "./"
      dockerfile: "Dockerfile"

    depends_on:
      - db
    ports:
      - "8069:8069"


  db:
    image: postgres:15

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata

    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: